root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  cmd = "go build -o bin/app ./cmd/app && curl http://localhost:9999/trigger"
  args_bin = []
  bin = "./bin/app"
  delay = 0
  exclude_dir = ["bin", "", "public/uploads", "node_modules", "testdata", "cmd/utils", "tmp"]
  exclude_file = []
  exclude_regex = ["_test.go", ".*_templ.go", ".*_templ.txt"]
  exclude_unchanged = true
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "templ", "html", "css"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = true
  post_cmd = ["make postcmd"]

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = true
  time = true

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = true
  keep_scroll = true